### ISSUE TITLE
Why was pointfree dot replaced by ^ ?

### ISSUE THREAD

**Issue by avanov** [thyeem/foc#2]
The previous version had better ergonomics. 
This version makes it uglier, doesn't translate verbatim from Haskell, and requires more fingers to type

**Comment by thyeem** [comment]
Thanks for your comment.
I completely agree. That was my concern, too. The caret symbol is not only very ugly but also misleading.
[So, I reverted to using dot notation again.](https://github.com/thyeem/foc/blob/main/foc/__init__.py#L232)

Like the expression `(_ + 5) . (8 * _)` _Syntax Error_ cannot be caught without manipulating `ast`. To addrress this, I had to the rule for `.` composition:
> Wrap the functions in `fx` when using lambda expressions and `.`

All my test have passed, but I would appreciate any feedback on potential issues it might have.

As you know, using the `.` symbol for function composition requires me to work on `__getattr__`.
Overriding `__getattr__`, so-called an attribute fallback, is quite risky compared to other noraml binary operator like `__xor__`, `__or__`, `__mul__`, and so on. That was the primary reason I decided to avoid using `.` symbol for composition operator.

Thanks for your suggestion and, I hope you enyoy it!

**Comment by avanov** [comment]
@thyeem oh wow, brilliant! Thanks for reconsidering it!
